/**
 * Các loại sự kiện đồng bộ hóa dữ liệu
 */
export const SYNC_EVENT_TYPE = {
  VISIT_SERVICE_UPDATED: 'VISIT_SERVICE_UPDATED',
  VISIT_TRANSLATION_UPDATED: 'VISIT_TRANSLATION_UPDATED',
  HOTEL_SERVICE_UPDATED: 'HOTEL_SERVICE_UPDATED',
  GUIDE_PRICE_SERVICE_UPDATED: 'GUIDE_PRICE_SERVICE_UPDATED',
  GUIDE_ALLOWANCE_SERVICE_UPDATED: 'GUIDE_ALLOWANCE_SERVICE_UPDATED',
  KM_SERVICE_UPDATED: 'KM_SERVICE_UPDATED',
  LOCATION_UPDATED: 'LOCATION_UPDATED'
};

/**
 * Các loại sự kiện khác
 */
export const EVENT_TYPE = {
  SET_PAX: 'SET_PAX',
  SET_STAR_RATING: 'SET_STAR_RATING',
  SET_NUMBER_OF_DAYS: 'SET_NUMBER_OF_DAYS',
  SET_TITLE: 'SET_TITLE',
  SET_CUSTOMER_NAME: 'SET_CUSTOMER_NAME',
  SET_CUSTOMER_SURNAME: 'SET_CUSTOMER_SURNAME',
  SET_CUSTOMER_START_DATE: 'SET_CUSTOMER_START_DATE',
  ADD_DAY: 'ADD_DAY',
  REMOVE_DAY: 'REMOVE_DAY',
  REORDER_DAY: 'REORDER_DAY',
  ADD_SERVICE: 'ADD_SERVICE',
  REMOVE_SERVICE: 'REMOVE_SERVICE',
  REORDER_SERVICE: 'REORDER_SERVICE',
  TOGGLE_SERVICE_SELECTION: 'TOGGLE_SERVICE_SELECTION',
  MOVE_SERVICE_TIME: 'MOVE_SERVICE_TIME',
};
